---
- hosts: Prueba
  tasks:
  - name: "SCORED | 5.1.1.1 | PATCH | Ensure cron daemon is enabled"
    service:
      name: crond
      enabled: yes

  - name: "SCORED | 5.1.1.2 | PATCH | Ensure permissions on /etc/crontab are configured"
    file:
      dest: /etc/crontab
      owner: root
      group: root
      mode: 0600

  - name: "SCORED | 5.1.1.3 | PATCH | Ensure permissions on /etc/cron.hourly are configured"
    file:
      dest: /etc/cron.hourly
      state: directory
      owner: root
      group: root
      mode: 0700

  - name: "SCORED | 5.1.1.4 | PATCH | Ensure permissions on /etc/cron.daily are configured"
    file:
      dest: /etc/cron.daily
      state: directory
      owner: root
      group: root
      mode: 0700

  - name: "SCORED | 5.1.1.5 | PATCH | Ensure permissions on /etc/cron.weekly are configured"
    file:
      dest: /etc/cron.weekly
      state: directory
      owner: root
      group: root
      mode: 0700

  - name: "SCORED | 5.1.1.6 | PATCH | Ensure permissions on /etc/cron.monthly are configured"
    file:
      dest: /etc/cron.monthly
      state: directory
      owner: root
      group: root
      mode: 0700

  - name: "SCORED | 5.1.1.7 | PATCH | Ensure permissions on /etc/cron.d are configured"
    file:
      dest: /etc/cron.d
      state: directory
      owner: root
      group: root
      mode: 0700

  - name: "SCORED | 5.1.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
    block:
      - name: "SCORED | 5.1.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
        file:
            dest: /etc/at.deny
            state: absent

      - name: "SCORED | 5.1.1.8 | PATCH | Check if at.allow exists"
        stat:
            path: "/etc/at.allow"
        register: p

      - name: "SCORED | 5.1.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
        file:
            dest: /etc/at.allow
            state: '{{ "file" if  p.stat.exists else "touch" }}'
            owner: root
            group: root
            mode: 0600

      - name: "SCORED | 5.1.1.9 | PATCH | Ensure at/cron is restricted to authorized users"
        file:
            dest: /etc/cron.deny
            state: absent

      - name: "SCORED | 5.1.1.9 | PATCH | Check if cron.allow exists"
        stat:
            path: "/etc/cron.allow"
        register: p

      - name: "SCORED | 5.1.1.9 | PATCH | Ensure at/cron is restricted to authorized users"
        file:
            dest: /etc/cron.allow
            state: '{{ "file" if  p.stat.exists else "touch" }}'
            owner: root
            group: root
            mode: 0600
