---
- hosts: Prueba
  tasks:

  - name: "SCORED | 5.1.5.1 | PATCH | Banner advertencia para servicios de inicio de sesión estándar"
    shell: 'echo "Authorized uses only. All activity may be monitored and reported." > /etc/issue'
    changed_when: no
  - name: "SCORED | 5.1.5.1 | PATCH | Banner advertencia para servicios de inicio de sesión estándar"
    shell: 'echo "Authorized uses only. All activity may be monitored and reported." > /etc/issue.net'
    changed_when: no
  - name: "SCORED | 5.1.5.1 | PATCH | Banner advertencia para servicios de inicio de sesión estándar"
    file:
      path: /etc/issue.net
      state: file
      mode: '0644'
      owner: root
      group: root

  - name: "SCORED | 5.1.5.1 | PATCH | Banner advertencia para servicios de inicio de sesión estándar"
    file:
      path: /etc/motd
      state: file
      mode: '0644'
      owner: root
      group: root

  - name: "SCORED | 5.1.5.1 | PATCH | Banner advertencia para servicios de inicio de sesión estándar"
    file:
      path: /etc/issue
      state: file
      mode: '0644'
      owner: root
      group: root

