---
- hosts: Prueba
  tasks:
  - name: "SCORED | 5.1.2.1| PATCH | Ensure SSH Protocol is set to 2"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^Protocol'
      line: 'Protocol 2'
 
  - name: "SCORED | 5.1.2.2 | PATCH | Ensure SSH LogLevel is set to INFO"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^LogLevel'
      line: 'LogLevel INFO'

  - name: "SCORED | 5.1.2.3 | PATCH | Ensure permissions on /etc/ssh/sshd_config are configured"
    file:
      dest: /etc/ssh/sshd_config
      state: file
      owner: root
      group: root
      mode: 0600

  - name: "SCORED | 5.1.2.4 | PATCH | Ensure SSH X11 forwarding is disabled"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^X11Forwarding'
      line: 'X11Forwarding no'

  - name: "SCORED | 5.1.2.5 | PATCH | Ensure SSH MaxAuthTries is set to 4 or less"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^(#)?MaxAuthTries \d'
      line: 'MaxAuthTries 4'

  - name: "SCORED | 5.1.2.6 | PATCH | Ensure SSH IgnoreRhosts is enabled"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^IgnoreRhosts'
      line: 'IgnoreRhosts yes'

  - name: "SCORED | 5.1.2.9 | PATCH | Ensure SSH PermitEmptyPasswords is disabled"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'

  - name: "SCORED | 5.1.2.11 | PATCH | Ensure only approved ciphers are used"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^Ciphers'
      line: "Ciphers aes256-ctr,aes192-ctr,aes128-ctr"

  - name: "SCORED | 5.1.2.11| PATCH | Ensure only approved MAC algorithms are used"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'
      create: yes

  - name: "SCORED | 5.1.2.12 | PATCH | Ensure SSH Idle Timeout Interval is configured"
    block:
      - name: "SCORED | 5.1.2.12 | PATCH | Ensure SSH Idle Timeout Interval is configured"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^ClientAliveInterval'
            line: "ClientAliveInterval 300"

      - name: "SCORED | 5.1.2.12 | PATCH | Ensure SSH ClientAliveCountMax set to <= 3"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^ClientAliveCountMax'
            line: "ClientAliveCountMax 0"
  - name: "SCORED | 5.1.2.13 | PATCH | Ensure SSH LoginGraceTime is set to one minute or less"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^LoginGraceTime'
      line: "LoginGraceTime 60"
  - name: "SCORED | 5.1.2.16 | PATCH | Ensure SSH warning banner is configured"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^Banner'
      line: 'Banner /opt/banner_inicio'
  - name: "Copia Banner"
    copy:
      src: /opt/banner_inicio
      dest: /opt/


