---
- hosts: Prueba
  tasks:

  - name: "SCORED |5.3.1.1 | PATCH | Ensure IP forwarding is disabled"
    lineinfile:
      path: /etc/sysctl.conf
      line: "net.ipv4.ip_forward = 0"
      state: present

  - name: "SCORED |5.3.1.2 | PATCH | net.ipv4.conf.all.send_redirects"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.conf.all.send_redirects = 0"
      state: present
       
  - name: "SCORED |5.3.1.2 | PATCH | net.ipv4.conf.default.send_redirects"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.conf.default.send_redirects = 0"
      state: present
      
  - name: "SCORED |5.3.2.1 | PATCH | net.ipv4.conf.all.accept_source_route"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.conf.all.accept_source_route = 0"
      state: present
      
  - name: "SCORED |5.3.2.1 | PATCH | net.ipv4.conf.default.accept_source_route"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.conf.default.accept_source_route = 0"
      state: present
      
  - name: "SCORED |5.3.2.2 | PATCH | net.ipv4.conf.all.accept_redirects"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.conf.all.accept_redirects = 0"
      state: present
      
  - name: "SCORED |5.3.2.2 | PATCH | net.ipv4.conf.default.accept_redirects"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.conf.default.accept_redirects = 0"
      state: present

  - name: "SCORED |5.3.2.3 | PATCH | net.ipv4.conf.all.secure_redirects"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.conf.all.secure_redirects = 0"
      state: present

  - name: "SCORED |5.3.2.3 | PATCH | net.ipv4.conf.default.secure_redirects"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.conf.default.secure_redirects = 0"
      state: present
      
  - name: "SCORED |5.3.2.4 | PATCH | net.ipv4.conf.all.log_martians"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.conf.all.log_martians = 1"
      state: present
      
  - name: "SCORED |5.3.2.4 | PATCH | net.ipv4.conf.default.log_martians"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.conf.default.log_martians = 1"
      state: present
      
  - name: "SCORED |5.3.2.5 | PATCH | net.ipv4.icmp_echo_ignore_broadcasts"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.icmp_echo_ignore_broadcasts = 1"
      state: present
  
  - name: "SCORED |5.3.2.6 | PATCH | net.ipv4.icmp_ignore_bogus_error_responses"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.icmp_ignore_bogus_error_responses = 1"
      state: present

  - name: "SCORED |5.3.2.7 | PATCH | net.ipv4.conf.all.rp_filter"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.conf.all.rp_filter = 1"
      state: present

  - name: "SCORED |5.3.2.7 | PATCH | net.ipv4.conf.default.rp_filter"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.conf.default.rp_filter = 1"
      state: present

  - name: "SCORED |5.3.2.7 | PATCH | net.ipv4.tcp_syncookies"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.tcp_syncookies = 1"
      state: present

  - name: "SCORED |5.3.2 | PATCH | net.ipv4.route.flush"
    lineinfile:
      path: /etc/sysctl.conf
      line : "net.ipv4.route.flush = 1"
      state: present

  - name: "SCORED | 5.3.4.1 | PATCH | Ensure IPv6 router advertisements are not accepted"
    lineinfile:
      path: /etc/sysctl.conf
      line: "net.ipv6.conf.all.accept_ra = 0"
      state: present

  - name: "SCORED | 5.3.4.1 | PATCH | Ensure IPv6 router advertisements are not accepted"
    lineinfile:
      path: /etc/sysctl.conf
      line: "net.ipv6.conf.default.accept_ra = 0"
      state: present

  - name: "SCORED | 5.3.4.1 | PATCH | Ensure IPv6 redirects are not accepted"
    lineinfile:
      path: /etc/sysctl.conf
      line: "net.ipv6.conf.all.accept_redirects = 0"
      state: present

  - name: "SCORED | 5.3.4.1 | PATCH | Ensure IPv6 router redirects are not accepted"
    lineinfile:
      path: /etc/sysctl.conf
      line: "net.ipv6.conf.default.accept_redirects = 0"
      state: present

  - name: "SCORED | 5.4.6.2 | PATCH | Ensure address space layout randomisation (ASLR) is enabled"
    lineinfile:
      path: /etc/sysctl.conf
      line: "kernel.randomize_va_space = 2"
      state: present

  - name: "SCORED | 5.4.6.1 | PATCH | Ensure core dumps are restricted"
    lineinfile:
      path: /etc/sysctl.conf
      line: "fs.suid_dumpable = 0"
      state: present

  - name: "NOTSCORED | 5.3.4.3 | PATCH | Ensure IPv6 is disabled"
    lineinfile:
      dest: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=.*(?!.*ipv6\.disable=1)\"[^\"]+)(\".*)'
      line: '\1 ipv6.disable=1\2'
      backrefs: yes

  - name: "NOTSCORED | 5.3.4.3 | PATCH | Ensure IPv6 is disabled (sysctl)"
    blockinfile:
      path: /etc/sysctl.d/00-CIS.conf
      block: |
        net.ipv6.conf.all.disable_ipv6 = 1
        net.ipv6.conf.default.disable_ipv6 = 1
        net.ipv6.conf.lo.disable_ipv6 = 1
      create: yes

  - name: "NOTSCORED | 5.3.4.3 | PATCH | Ensure IPv6 is disabled (sysctl)"
    blockinfile:
      path: /etc/modprobe.d/ipv6.conf
      block: |
        options ipv6 disable=1
      create: yes
  - name: "SCORED | 5.3.5.1 | PATCH | Ensure TCP Wrappers is installed"
    yum:
      name: tcp_wrappers
      state: present
    register: tcp_wrappers_present
    retries: 3
    until: tcp_wrappers_present is succeeded
    delay: 5

  - name: "SCORED | 5.3.5.3 | PATCH | Ensure permissions on /etc/hosts.allow are configured"
    file:
      dest: /etc/hosts.allow
      state: file
      owner: root
      group: root
      mode: 0644

  - name: "SCORED | 5.3.5.3 | PATCH | Ensure permissions on /etc/hosts.allow are configured"
    file:
      dest: /etc/hosts.deny
      state: file
      owner: root
      group: root
      mode: 0644
