---
- hosts: Prueba
  tasks:
  - name: "SCORED | 5.4.5.3 | PATCH | Ensure password hashing algorithm is SHA-512 command"
    shell: echo -e "abc123\nabc123" | grub2-mkpasswd-pbkdf2> /tmp/testuser 
  - name: "SCORED | 5.1.3.1 | PATCH | Ensure password hashing algorithm is SHA-512 command"
    shell: 'sed -e "s|PBKDF2 hash of your password is |GRUB2_PASSWORD=|" -e "s|Enter password:||" -e "s|Reenter password:||" /tmp/testuser > /boot/grub2/user.cfg'
    args:
      warn: no

  - name: "SCORED | 5.4.5.3 | PATCH | Ensure permissions on /boot/grub2/user.cfg are configured"
    file:
      dest: /boot/grub2/user.cfg
      state: file
      owner: root
      group: root
      mode: 0600
  - name: "SCORED | 5.4.5.3 | PATCH | Ensure permissions on /etc/grub2.cfg are configured"
    file:
      dest: /etc/grub2.cfg
      state: file
      owner: root
      group: root
      mode: 0600
  - name: "SCORED | 5.4.5.4 | PATCH |systemctl set-default multi-user.target"
    shell: systemctl set-default multi-user.target
  - name: "SCORED | 5.4.6.1 | PATCH | Ensure core dumps are restricted"
    lineinfile:
      state: present
      dest: /etc/security/limits.conf
      regexp: '^#?\\*.*core'
      line: '*                hard    core            0'
      insertbefore: '^# End of file'

  - name: "SCORED | 5.4.6.1 | PATCH | Ensure core dumps are restricted"
    sysctl:
      name: fs.suid_dumpable
      value: "0"
      state: present
      reload: yes
      sysctl_set: yes
      ignoreerrors: yes

  - name: "SCORED | 5.4.6.2 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
    sysctl:
      name: kernel.randomize_va_space
      value: "2"
      state: present
      reload: yes
      sysctl_set: yes
      ignoreerrors: yes

  - name: "NOTSCORED | 3.3.3 | PATCH | Ensure IPv6 is disabled"
    lineinfile:
      dest: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=.*(?!.*ipv6\.disable=1)\"[^\"]+)(\".*)'
      line: '\1 ipv6.disable=1\2'
      backrefs: yes
  - name: "NOTSCORED | 3.3.3 | PATCH | Ensure IPv6 is disabled command-mkgrub"
    shell: 'grub2-mkconfig -o /boot/grub2/grub.cfg'
    args:
      warn: no

